### ISSUE TITLE
Summary of Denis Migdal's issues

### ISSUE THREAD

**Issue by denis-migdal** [brython-dev/brython#2250]
Hi,

As I posted LOT of issues, I make a summary here so I can keep track of it :

**Open issues :**

- [ ] #2249 window.Date != window.Date
    - [ ] use Proxy + Symbol : HUGE performances increase possible in memory. In execution speed, way slower compared to direct access, but may be way quicker compare to rebuilding objects on demand (?).
- [ ] #2248 null value cause issues.
      - [ ] also unsafe/asymmetric null/undefined/None conversions (maybe linked to #2249)
- [ ] #2247  "bases[0].$js_func is undefined" when doing inheritance (maybe linked to #2244).
- [ ] #2245 Document that `DOMStringMap` , when keys does not exists raise exception in Brython while it returns `undefined` in JS ? (issue will be close if answer is "no").
- [ ] #2240 `browser.template.Template` isn't safe. Safer version proposed ([code provided](https://github.com/brython-dev/brython/issues/2240#issuecomment-1740052206)).
   - [ ]  `browser.template.Template` can't be done on `body` (TypeError: DOMNode object doesn't support selection by selector)
- [ ] #2236 Infinite loop when using `browser.template.Template` on a Webcomponent (likely linked to #2240 )
- [ ] #2234 
    - [ ] bug in `webcomponent.define()` : checking only the bases of the class. Need to check the bases of its bases recursively [(code provided)](https://github.com/brython-dev/brython/issues/2234#issuecomment-1737854902).
    - [ ] Document "attachShadow not authorized in some Element" ? (will be check if anwser is "no")
    - [ ] Document "createElement()" issue with Element inserting childs in constructors without `attachShadow()` ([link](https://github.com/brython-dev/brython/issues/2234#issuecomment-1739937553)) ? (will be check if anwser is "no")
    - [X] maketag with customized built-in element

**Closed issues :**

- [X] #2239 : third parameter in webcomponent.define
- [X] #2244 : bug for classes that inherit objects like window.HTMLElement

**In the Google group discussion :**

- [ ] Add an option to script tag to auto-import windows into globals() ? (I have Brython code for that)
- [ ] [Modify documentation structure ?](https://groups.google.com/g/brython/c/9B_I9K7NGDA/m/qPo_4VRAAQAJ) (I can get students on it for a project)
- [ ] Add benchmarks ? (I can get students on it for a project)
- [ ] Cookbooks with JS/DOM API ? (I can write them).
- [ ] Webpack loader for Brython (I can code very simple ones)
- [ ] Being able to reduce brython.js just like what is done with brython-cli modules for brython_stdlib.js ?

Cordially,

**Comment by denis-migdal** [comment]
@PierreQuentel  I restructured my summary, hope it'll help you.

**Comment by denis-migdal** [comment]
I moved the optimizations issues to [[2260]](https://github.com/brython-dev/brython/issues/2260) and made a summary at the top of it.
